app/toto/views.py
from flask import Blueprint, make_response
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file
import socket
from datetime import datetime
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple
from flask_restful import Api, Resource, reqparse
from sqlalchemy import func, desc, asc

from app.common.decorator import return_500_if_errors, login_required
from app.db import *
from config import credentials, SECRET_KEY
from app.cache import cache
from app.common.function import fetch_spread_sheet, format_url_title, send_discord_alert_log
from config import SECRET_KEY
import random
from collections import defaultdict

toto_bp = Blueprint('toto', __name__)

toto_term = "23 수능"
toto_source = ["2023학년도 수능특강", "2023학년도 수능완성"]
pick_deadline = datetime(2022, 11, 11, 23, 59, 59)
toto_real_result = [120, 122, 124, 126, 128, 130]
is_result_open = False


def is_toto_target_munhak(munhak_row):
    if munhak_row["source"] in toto_source:
        return True
    else:
        return False


@toto_bp.route('/')
def toto_index():
    munhak_rows_data_dict = cache.get("munhak_rows_data_dict")



    data = {
        "term" : toto_term,
        "pick_deadline" : f"{pick_deadline.month}/{pick_deadline.day}"
    }
    data["is_result_open"] = is_result_open

    try:
        user_seq = session["user"]["user_seq"]
    except:
        user_seq = None
    data["user_seq"] = user_seq

    print(data)

    if datetime.now() < pick_deadline:
        # 픽 가능
        data["is_pick_available"] = True
        pick_rows = TotoPick.query.filter_by(term=toto_term).all()

        pick_list = [{
            "nickname": x.user.nickname, "pick1": munhak_rows_data_dict.get(x.pick1),
            "pick2": munhak_rows_data_dict.get(x.pick2), "pick3": munhak_rows_data_dict.get(x.pick3),
            "pick4": munhak_rows_data_dict.get(x.pick4),
            "pick5": munhak_rows_data_dict.get(x.pick5), "pick6": munhak_rows_data_dict.get(x.pick6),
            "date": x.add_date.strftime("%Y-%m-%d"), "user_seq": x.user.user_seq
        } for x in pick_rows]

        print(pick_list)

        random.shuffle(pick_list)
        data["pick_list"] = pick_list

        resp = make_response(render_template("toto/index.html", data=data))
        resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
        return resp
    else:
        # 픽 종료
        data["is_pick_available"] = False
        if is_result_open:
            pass
        else:
            pick_rows = TotoPick.query.all()

            pick_list = [{
                "nickname": x.user.nickname, "pick1": munhak_rows_data_dict.get(x.pick1),
                "pick2": munhak_rows_data_dict.get(x.pick2), "pick3": munhak_rows_data_dict.get(x.pick3),
                "pick4": munhak_rows_data_dict.get(x.pick4),
                "pick5": munhak_rows_data_dict.get(x.pick5), "pick6": munhak_rows_data_dict.get(x.pick6),
                "date": x.add_date.strftime("%Y-%m-%d"), "user_seq": x.user.user_seq
            } for x in pick_rows]

            random.shuffle(pick_list)
            data["pick_list"] = pick_list

            resp = make_response(render_template("toto/index.html", data=data))
            resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None,
                            path='/')
            return resp


@toto_bp.route('/detail/<int:munhak_seq>/')
def toto_munhak_detail(munhak_seq):
    data = {}

    munhak_rows = cache.get("munhak_rows_data")
    munhak_rows_data_dict = cache.get("munhak_rows_data_dict")

    target_munhak_row = munhak_rows_data_dict.get(munhak_seq, None)
    if target_munhak_row is None:
        return abort(404)

    data["munhak_row"] = target_munhak_row

    title_same_rows = []
    writer_same_rows = []

    for munhak_row in munhak_rows:
        if target_munhak_row["title"] == munhak_row["title"]:
            title_same_rows.append(munhak_row)
        elif target_munhak_row["writer"] != "작자 미상" and target_munhak_row["writer"] == munhak_row["writer"]:
            writer_same_rows.append(munhak_row)
    data["title_same_rows"] = list(reversed(title_same_rows))
    data["writer_same_rows"] = list(reversed(writer_same_rows))

    return jsonify(data)


@toto_bp.route("/add", methods=["GET", "POST"])
@login_required
def add_pick():
    user_seq = session["user"]["user_seq"]
    args = request.form

    pick_list_tmp = [args.get(f"pick{i}", "NaN") for i in range(1, 7)]
    pick_list = []
    for pick in pick_list_tmp:
        if pick == "NaN":
            pick_list.append(None)
        else:
            pick_list.append(int(pick))

    print(args, pick_list)
    # return

    if len(pick_list) != 6:
        return abort(400)

    pick_list_not_none = [x for x in pick_list if x is not None]

    if not len(pick_list_not_none) >= 2 and len(pick_list_not_none) <= 6:
        print("@#@#$")
        return abort(400)

    if len(set(pick_list_not_none)) != len(pick_list_not_none):
        return abort(400)

    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows = copy.deepcopy(munhak_rows_data)

    for pick in pick_list_not_none:
        munhak_row = [x for x in munhak_rows if x["munhak_seq"] == pick and is_toto_target_munhak(x)]
        print(munhak_row, pick)
        if len(munhak_row) == 0:
            return abort(404)

    old_pick_row = TotoPick.query.filter_by(user_seq=user_seq).first()
    if old_pick_row is not None:
        db.session.delete(old_pick_row)

    pick_row = TotoPick(
        user_seq=user_seq,
        term=toto_term,
        pick1=pick_list[0],
        pick2=pick_list[1],
        pick3=pick_list[2],
        pick4=pick_list[3],
        pick5=pick_list[4],
        pick6=pick_list[5],
        add_date=datetime.now(),
    )

    db.session.add(pick_row)
    db.session.commit()

    send_discord_alert_log(f"Pick add! {str(pick_list)}")

    return "", 200


@toto_bp.route("/delete", methods=["GET", "POST"])
@login_required
def delete_pick():
    user_seq = session["user"]["user_seq"]

    old_pick_row = TotoPick.query.filter_by(user_seq=user_seq, term=toto_term).first()
    if old_pick_row is None:
        return abort(404)

    db.session.delete(old_pick_row)
    db.session.commit()
    return "", 200


@toto_bp.route("/pick", methods=["GET", "POST"])
@login_required
def pick_toto_form():
    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows_data_dict = cache.get("munhak_rows_data_dict")

    munhak_rows = copy.deepcopy(munhak_rows_data)

    user_seq = session["user"]["user_seq"]

    data = {
        "term" : toto_term
    }
    munhak_group_data = defaultdict(list)
    for munhak_row in munhak_rows:
        if is_toto_target_munhak(munhak_row):
            munhak_group_data[munhak_row["category"]].append(munhak_row)
    data["munhak_group_data"] = munhak_group_data

    old_pick_data = []

    old_pick_row = TotoPick.query.filter_by(user_seq=user_seq, term=toto_term).first()
    if old_pick_row is not None:
        for pick in [old_pick_row.pick1, old_pick_row.pick2, old_pick_row.pick3, old_pick_row.pick4, old_pick_row.pick5,
                     old_pick_row.pick6]:
            if pick is not None:
                old_pick_data.append(munhak_rows_data_dict[pick])

    data["old_pick_data"] = old_pick_data
    print(data)

    r = make_response(render_template("./toto/toto_form.html", data=data))
    r.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return r

templates/toto/index.html
{% extends "layout.html" %}


{% block style %}
    <title>{{ data.term }} 문학작품 또또 - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">


{% endblock %}

{% block main %}

    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/toto.css') }}">

    <div id="contentContainer">
        <div id="upperContainer" class="">
            <div id="totoTitle">
                {{ data.term }} 문학 작품 또또
            </div>
            <div id="totoDescription">
                {{ data.term }}에 연계될 것 같은 EBS 작품은? (~{{ data.pick_deadline }} 까지 선택)

            </div>


        </div>


        <div id="underContainer">
            <div class="d-flex justify-content-end">
                <div></div>
                {% if data.is_pick_available %}
                <div id="goPickButton" class="btn btn-outline-primary">
                    <i class="fas fa-edit"></i> 선택 / 수정

                </div>
                {% endif %}
            </div>
            <div id="userContainer">
                {% for user in data.pick_list %}
                    <div class="userWrapper">

                        <div class="pickContainer">
                            {% for pick in [user.pick1, user.pick2] %}
                                {% if pick != None %}
                                    <div class="pickWrapper"
                                         onclick="movePage(`{{ url_for('board.munhak_board_detail', munhak_seq=pick.munhak_seq) }}`);">{{ pick.writer }},
                                        『{{ pick.title }}』
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% for pick in [user.pick3, user.pick4, user.pick5, user.pick6] %}
                                {% if pick != None %}
                                    {% if data.is_pick_available == False or user.user_seq == data.user_seq or data.user_seq == 1 %}
                                        <div class="pickWrapper"
                                             onclick="movePage(`{{ url_for('board.munhak_board_detail', munhak_seq=pick.munhak_seq) }}`);">{{ pick.writer }},
                                            『{{ pick.title }}』
                                        </div>


                                    {% else %}
                                        <div class="pickNotPublic">
                                            <i class="fa fa-question pickNotPublicIcon"></i>
                                        </div>
                                    {% endif %}
                                {% endif %}


                            {% endfor %}
                        </div>

                        <div class="underPickInfo">
                            <div class="userNickname">
                                <i class="fas fa-user"></i> {{ user.nickname }}
                            </div>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <div class="pickDatetime">
                                <i class="fas fa-calendar-day"></i> {{ user.date }}
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
        </div>
        <div id="totoDescription2">
            2 작품 이상 적중 시 소정의 상품을 드립니다 (＠＾０＾)
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        (() => {
            function warningToast(message) {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": true,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "2000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                toastr["warning"](message, "오류")
            }

            let is_logined = {{ "true" if "user" in session else "false"}};
            $(document).ready(function () {

            });
            $("#goPickButton").on("click", function () {
                if (!is_logined) {
                    warningToast("로그인이 필요합니다!");
                    return;
                }
                movePage(`/toto/pick`);

            });

        })();

    </script>
{% endblock %}

templates/toto/toto_form.html
{% extends "layout.html" %}


{% block style %}
    <title>{{ data.term }} 문학작품 또또 - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">



{% endblock %}

{% block main %}
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/toto_form.css') }}">

    <div id="contentContainer">
        <div id="upperContainer" class="">
            <div id="totoTitle">
                문학 작품 선택
            </div>
            <div id="totoDescription">
                문학 작품 2~6개를 고르고 그 중 다른 사람들에게 공개할 2개를 선택해주세요!
            </div>


        </div>


        <div id="formUnderContainer">
            <div id="leftContainer">


                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    {% for category in data.munhak_group_data.keys() %}

                        <li class="nav-item" role="presentation">
                            <a class="nav-link {{ 'active' if loop.index0 == 0 }}" id="pills-{{ category }}-tab"
                               data-toggle="pill" href="#pills-{{ category }}"
                               role="tab"
                               aria-controls="pills-{{ category }}"
                               aria-selected="{{ 'true' if loop.index0 == 0 }}">{{ category }}</a>
                        </li>
                    {% endfor %}


                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    {% for category, munhak_rows in data.munhak_group_data.items() %}

                        <div class="tab-pane munhakContainer fade {{ 'show active' if loop.index0 == 0 }}"
                             id="pills-{{ category }}"
                             role="tabpanel"
                             aria-labelledby="pills-home-tab">


                            {% for munhak_row in munhak_rows %}
                                <div class="munhakWrapper" data-seq="{{ munhak_row.munhak_seq }}">
                                    {% if '특강' in munhak_row.source %}
                                        <span class="badge badge-pill badge-success">수특</span>
                                    {% else %}
                                        <span class="badge badge-pill badge-danger">수완</span>
                                    {% endif %}
                                    &nbsp;


                                    <span class="munhakTitle">
                                        {{ munhak_row.writer }}, 『{{ munhak_row.title }}』
                                    </span>
                                </div>
                            {% endfor %}


                        </div>

                    {% endfor %}

                </div>
            </div>

            <div id="rightContainer">
                {#                <div id="selectDescription">#}
                {#                    다른 사람들에게 공개할 2개의 문학 작품을 선택해주세요!#}
                {#                </div>#}
                <div id="selectMunhakContainer">

                </div>
            </div>
        </div>


    </div>
    <div class="d-flex justify-content-end">
        <div></div>
        <div id="submitButton" class="btn btn-outline-primary   ">
            제출
        </div>
    </div>


{% endblock %}

{% block script %}
    <script>
        (() => {

            let munhak_list = [];

            munhak_list = [
                {% for pick in data.old_pick_data %}
                    {% if pick != None %}
                        {
                            "title": "{{ pick.writer }}, 『{{ pick.title }}』", "munhak_seq": "{{ pick.munhak_seq }}",
                            "is_public": {{ "true" if loop.index0 <= 1 else "false"}}
                        },
                    {% endif %}
                {% endfor %}
            ];

            refreshMunhakList();


            let public_cnt = 0;


            function refreshMunhakList() {

                let $container = $("#selectMunhakContainer");
                $container.html("")
                for (let munhak of munhak_list) {
                    $container.append(`
                        <div class="selectMunhakWrapper ${munhak.is_public ? 'active' : ''}" data-seq="${munhak.munhak_seq}">
                            <i class="far fa-check-circle selectMunhakCheck"></i>

                            <div class="selectMunhakTitle">
                            ${munhak.title}
                            </div>
                            <i class="far fa-trash-alt selectMunhakDelete"></i>
                        </div>

                    `)
                }
            }


            $(document).on("click", ".selectMunhakCheck", function (e) {
                let $target = $(e.target);
                let munhak_seq = $target.parent().attr("data-seq");

                public_cnt = 0;

                let target_i = -1;
                let origin_b = undefined;

                for (let i in munhak_list) {

                    if (munhak_list[i].munhak_seq === munhak_seq) {
                        target_i = i;
                        origin_b = munhak_list[i].is_public;

                    }
                    if (munhak_list[i].is_public === true) {
                        public_cnt += 1;
                    }
                }

                if (target_i !== -1) {
                    if (public_cnt >= 2) {
                        if (origin_b === false) {
                            //
                        } else {
                            munhak_list[target_i].is_public = false;
                        }
                    } else {
                        munhak_list[target_i].is_public = !munhak_list[target_i].is_public;
                    }
                }


                refreshMunhakList();

            });

            $(document).on("click", ".selectMunhakDelete", function (e) {
                let $target = $(e.target);
                let munhak_seq = $target.parent().attr("data-seq");
                for (let i in munhak_list) {

                    if (munhak_list[i].munhak_seq === munhak_seq) {
                        munhak_list = munhak_list.filter(x => x !== munhak_list[i]);
                        break;
                    }
                }
                refreshMunhakList();

            });

            $("#submitButton").on("click", function (e) {
                public_cnt = 0;

                public_list = [];
                unpublic_list = [];

                for (let i in munhak_list) {

                    if (munhak_list[i].is_public === true) {
                        public_list.push(munhak_list[i].munhak_seq);
                        public_cnt += 1;
                    } else {
                        unpublic_list.push(munhak_list[i].munhak_seq);
                    }
                }
                if (public_cnt !== 2 || munhak_list.length < 2 || munhak_list.length > 6) {
                    warningToast("다른 사람들에게 공개할 픽을 2개 골라주세요.");
                    return;
                }

                $.ajax({
                    type: "POST",
                    url: "{{ url_for("toto.add_pick") }}",
                    data: {
                        "pick1": parseInt(public_list[0]),
                        "pick2": parseInt(public_list[1]),
                        "pick3": parseInt(unpublic_list[0]),
                        "pick4": parseInt(unpublic_list[1]),
                        "pick5": parseInt(unpublic_list[2]),
                        "pick6": parseInt(unpublic_list[3]),
                    },
                    dataType: "json",
                    statusCode: {

                        200: function (data) {

                            console.log(data);
                            movePage("/toto");
                        }
                    }

                }).done(function (data) {
                    alert("!!!");

                })

            });

            function warningToast(message) {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": true,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "2000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                toastr["warning"](message, "오류")
            }


            $(".munhakWrapper").on("click", function (e) {
                let munhak_seq = $(this).attr("data-seq");
                let title = $(this).find(".munhakTitle").text().trim();

                if (munhak_list.length >= 6) {
                    warningToast("최대 6개까지 선택 가능합니다!")
                    return;
                }

                for (let munhak of munhak_list) {
                    if (munhak.munhak_seq === munhak_seq) {
                        return;
                    }
                }

                munhak_list.push({
                    "munhak_seq": munhak_seq, "title": title, "is_public": false,
                });
                refreshMunhakList();

            })
            $(document).ready(function () {

            });


        })();

    </script>
{% endblock %}