app/others/views.py
from flask import Blueprint, make_response
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file
import socket
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple
from flask_restful import Api, Resource, reqparse

from app.common.decorator import return_500_if_errors
from config import credentials, SECRET_KEY
from app.cache import cache
from app.common.function import fetch_spread_sheet
from config import SECRET_KEY

others_bp = Blueprint('others', __name__)


@others_bp.route('/update')
def update_():
    if request.args.get("key", None) != SECRET_KEY:
        return "error"

    len_data = fetch_spread_sheet()
    session.clear()
    return f"success! {len_data}"


@others_bp.route('/images/<path:path>')
def get_image(path):
    def get_absolute_path(path):
        import os
        script_dir = os.path.dirname(__file__)  # <-- absolute dir the script is in
        rel_path = path
        abs_file_path = os.path.join(script_dir, rel_path)
        return abs_file_path

    return send_file(
        get_absolute_path(f"../../images/{path}"),
        mimetype='image/png',
        attachment_filename='snapshot.png',
        cache_timeout=0
    )


@others_bp.route("/index")
def index():
    resp = make_response(render_template("index.html"))
    resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return resp

app/quiz/views.py
import string
from itertools import groupby

from flask import Blueprint
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file
import socket
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple, defaultdict
from flask_restful import Api, Resource, reqparse
from sqlalchemy import desc, asc
import uuid

from app.common.encrypt import simpleEnDecrypt
from config import credentials, SECRET_KEY
from app.cache import cache
from app.common.function import fetch_spread_sheet, send_discord_alert_log, edit_distance
from app.db import *
from datetime import datetime
from flask_socketio import SocketIO
from flask_socketio import emit, join_room, leave_room, rooms

from app.socket import socketio

quiz_bp = Blueprint('quiz', __name__)


@quiz_bp.route('/')
def index():
    munhak_rows_data = cache.get("munhak_quiz_rows_data")

    munhak_rows = copy.deepcopy(munhak_rows_data)

    source_dict = cache.get("source_dict")

    data = {
        "total_munhak": len(munhak_rows),
        "source_list": sorted(set([munhak_row["source"] for munhak_row in munhak_rows])),
        "source_dict": source_dict
    }
    print(data)

    session["quiz_count"] = 0
    return render_template("quiz/index.html", data=data)


def make_quiz(include_munhak_rows, not_selected_munhak_rows, all_munhak_rows=None):
    if all_munhak_rows is None:
        all_munhak_rows = include_munhak_rows

    # import time
    # start = time.time()  #

    correct_munhak_row = random.choice(not_selected_munhak_rows)

    space_replaced_title = correct_munhak_row["title"].replace(" ", "")
    for _ in [munhak_row for munhak_row in all_munhak_rows if
              space_replaced_title == munhak_row["title"].replace(" ", "")]:
        all_munhak_rows.remove(_)  # 제목이 같은 건 선지에 넣지 않는다

    random.shuffle(all_munhak_rows)

    if random.random() <= 0.3:  # 30% 확률
        option_munhak_rows = [munhak_row for munhak_row in all_munhak_rows if
                              munhak_row["category"] == correct_munhak_row["category"]][0:3] + [correct_munhak_row]
    else:

        if random.random() <= 0.4:  # 28% 확률
            option_munhak_rows = []
            for munhak_row in all_munhak_rows:
                munhak_row["distance"] = edit_distance(munhak_row["title"].replace(" ", ""),
                                                       correct_munhak_row["title"].replace(" ", ""))

            distance_sorted_munhak_rows = sorted(all_munhak_rows, key=lambda x: x["distance"])
            distance_groupby_munhak_rows = groupby(distance_sorted_munhak_rows, key=lambda x: x["distance"], )

            c = 0

            for _, same_distance_munhak_rows in distance_groupby_munhak_rows:
                temp_list = list(same_distance_munhak_rows)
                random.shuffle(temp_list)
                for munhak_row in temp_list:
                    if c == 3:
                        break

                    if munhak_row["title"] in correct_munhak_row["title"] or correct_munhak_row["title"] in munhak_row[
                        "title"]:
                        continue

                    if munhak_row["title"] in [x["title"] for x in option_munhak_rows]:
                        continue

                    option_munhak_rows.append(munhak_row)
                    c += 1
                if c == 3:
                    break

            option_munhak_rows.append(correct_munhak_row)
        else:
            option_munhak_rows = all_munhak_rows[0:3] + [correct_munhak_row]

    random.shuffle(option_munhak_rows)
    correct = option_munhak_rows.index(correct_munhak_row)

    hint = random.choice(correct_munhak_row["keywords"])
    hint = hint.replace("\\", "")

    quiz_data = {
        "munhak_seq": correct_munhak_row["munhak_seq"],
        "source": correct_munhak_row["source"],
        "category": correct_munhak_row["category"],
        "hint": hint,
        "correct": correct,
        "options": [
            f"{munhak_row['writer']}, 『{munhak_row['title']}』" for munhak_row in option_munhak_rows
        ],
        "title": correct_munhak_row["title"],
        "writer": correct_munhak_row["writer"],
        "option_munhak_rows": option_munhak_rows
    }
    # print("time :", time.time() - start)
    return quiz_data


@quiz_bp.route('/get-quiz', methods=["GET", "POST"])
def get_quiz():
    # import time
    # time.sleep(1)
    if "exclude_quiz_source" not in session:
        session["exclude_quiz_source"] = []
    else:
        exclude_quiz_source = session["exclude_quiz_source"]
    munhak_rows_data = copy.deepcopy(cache.get("munhak_quiz_rows_data"))

    print(exclude_quiz_source)

    # munhak_rows_data = []

    def source_check(source):
        if source in exclude_quiz_source:
            return False
        else:
            return True

    include_munhak_rows_data = [munhak_row for munhak_row in munhak_rows_data if source_check(munhak_row["source"])]

    if "is_end" in session and session["is_end"] is True:
        session["quiz_count"] = 0
        session["total_munhak"] = len(include_munhak_rows_data)
        session["solved_quiz"] = []
        session["current_munhak"] = None
        session["is_end"] = False

    if "quiz_count" not in session:
        session["quiz_count"] = 0
        session["total_munhak"] = len(include_munhak_rows_data)
    if "solved_quiz" not in session:
        session["solved_quiz"] = []
    session["result"] = None

    quiz_no = session["quiz_count"] + 1
    solved_quiz = session["solved_quiz"]

    if "_id" not in session:
        session["_id"] = uuid.uuid4()

    if "current_munhak" not in session or session["current_munhak"] is None:

        # munhak_rows = Munhak.query.filter_by(is_available=True).all()

        include_munhak_rows = copy.deepcopy(include_munhak_rows_data)
        all_munhak_rows = copy.deepcopy(munhak_rows_data)

        not_solved_munhak_rows = [munhak_row for munhak_row in include_munhak_rows if
                                  munhak_row["munhak_seq"] not in solved_quiz]

        if len(not_solved_munhak_rows) == 0:  # 다 맞았을 때
            session["result"] = True
            return "wow", 404

        quiz_data = make_quiz(include_munhak_rows, not_solved_munhak_rows, all_munhak_rows=all_munhak_rows)

        session["correct"] = simpleEnDecrypt.encrypt(f"{quiz_data['correct']}:{uuid.uuid4()}")

        session["current_munhak"] = {
            "munhak_seq": quiz_data["munhak_seq"],
            "source": quiz_data["source"],
            "category": quiz_data["category"],
            "hint": quiz_data["hint"],
            # "title": correct_munhak_row["title"],
            # "writer": correct_munhak_row["writer"]
        }
        session["options"] = [munhak_row for munhak_row in quiz_data["option_munhak_rows"]]
        data = {
            "quiz_no": quiz_no,
            "type": "객관식",
            "category": quiz_data["category"],
            "hint": quiz_data["hint"],
            "options": quiz_data["options"],
            "total_munhak": len(include_munhak_rows_data)
        }
        print(data)
        #
        return render_template("quiz/quiz.html", data=data)
    else:
        # print(hint)
        data = {
            "quiz_no": quiz_no,
            "type": "객관식",
            "category": session["current_munhak"]["category"],
            "hint": session["current_munhak"]["hint"],
            "options": [
                f"{munhak_row['writer']}, 『{munhak_row['title']}』" for munhak_row in session["options"]
            ],
            "total_munhak": len(include_munhak_rows_data)
        }
        print(data)
        #
        return render_template("quiz/quiz.html", data=data)


@quiz_bp.route('/reset-quiz', methods=["GET", "POST"])
def reset_quiz():
    args = request.json

    source_dict = args["source_dict"]
    re = args["re"]

    if re:

        source_list = []
        for k, v in source_dict.items():
            if v is False:
                source_list.append(k)

        session["exclude_quiz_source"] = source_list

        session["quiz_count"] = 0
        session["solved_quiz"] = []
        session["current_munhak"] = None
        session["is_end"] = False

    return "succ", 200


@quiz_bp.route('/play')
def quiz():
    return render_template("quiz/quiz_container.html")


@quiz_bp.route("/answer", methods=["GET", "POST"])
def answer():
    print(session)
    option = request.form.get("option", None)
    if option is None or (not type(option) != int):
        return abort(400)
    option = int(option)

    try:

        correct = int(simpleEnDecrypt.decrypt(session["correct"]).split(":")[0])
    except:
        return abort(401)

    if correct is None:
        return abort(401)

    current_munhak = session["current_munhak"]
    if current_munhak is None:
        return abort(401)

    if correct == option:
        session["quiz_count"] += 1
        session["solved_quiz"].append(current_munhak["munhak_seq"])
        session["current_munhak"] = None
        # current_munhak = jsonify(current_munhak)
        return get_quiz()
    else:

        if "quiz_count" not in session:
            session["quiz_count"] = 0
        if "solved_quiz" not in session:
            # session["solved_quiz"] = []
            session["result"] = False

        return "failed", 404


@quiz_bp.route("/result", methods=["GET", "POST"])
def result():
    if "result" not in session:
        return redirect(url_for("quiz.index"))

    if "quiz_count" in session and session["quiz_count"] >= 3:
        send_discord_alert_log(f"{session['quiz_count']}개를 맞혔어요!")

    is_success = session["result"]
    session["is_end"] = True

    # session["quiz_count"] = 0
    # session["solved_quiz"] = []

app/user/views.py
from flask import Blueprint
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file, make_response
import socket
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple
from flask_restful import Api, Resource, reqparse

from app.common.decorator import return_500_if_errors, login_required
from config import credentials, SECRET_KEY, YOUTUBE_KEY
from app.cache import cache
from app.common.function import *
import requests
from app.db import *
import datetime
from datetime import datetime

user_bp = Blueprint('user', __name__)



@user_bp.route("/user/change-nickname", methods=["GET", "POST"])
@login_required
def change_nickname():
    args = request.form
    nickname = args.get("nickname", None)
    if nickname is None or (not (1 <= len(nickname.encode("cp949")) <= 16)):
        return abort(400)
    user_seq = session["user"]["user_seq"]
    user_row = User.query.filter_by(user_seq=user_seq).first()
    if user_row is None:
        return abort(401)

    user_row.nickname = nickname

    db.session.commit()

    session["user"] = user_row.as_dict()
    print(session)
    return jsonify({
        "message" : "정상적으로 처리되었습니다."
    }), 200



@user_bp.route('/my')
@login_required
def my_page():
    print(session["user"]["nickname"])
    resp = make_response(render_template("user/my_page.html"))
    resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return resp





@user_bp.route('/login')
def login_form():
    return render_template('user/login_form.html')



@user_bp.route('/register')
def register_form():
    return render_template('user/register_form.html')



@user_bp.route('/register-query', methods=["GET", "POST"])
def register_query():
    args = request.form
    nickname = args.get("nickname", None)
    if nickname is None or (not (1 <= len(nickname.encode("cp949")) <= 16)):
        return abort(400)
    cookies = request.cookies
    if "kakao-access-token" not in cookies:
        return abort(403)
    access_token = cookies["kakao-access-token"]
    if access_token is None or type(access_token) != str:
        return abort(400)

    res = requests.get("https://kapi.kakao.com/v1/user/access_token_info", headers={
        "Authorization": "Bearer " + access_token
    })

    kakao_id = str(json.loads(res.text)["id"])

    old_user_row = User.query.filter((User.nickname == nickname) | (User.social_id == kakao_id)).first()
    if old_user_row is not None:
        return abort(409)

    user_row = User(
        nickname=nickname,
        social_type="kakao",
        social_id=kakao_id,
        add_date=datetime.now()
    )
    db.session.add(user_row)
    db.session.commit()
    session["user"] = user_row.as_dict()

    send_discord_alert_log(f"새로운 회원! {nickname}")

    return make_response("", 200)



@user_bp.route('/login-query-kakao', methods=["GET", "POST"])
def login_query_kakao():


    args = request.form
    access_token = args.get("access_token", None)
    print(access_token)
    if access_token is None or type(access_token) != str:
        return abort(400)

    res = requests.get("https://kapi.kakao.com/v1/user/access_token_info", headers={
        "Authorization": "Bearer " + access_token
    })

    kakao_id = str(json.loads(res.text)["id"])

    user_row = User.query.filter_by(social_type="kakao", social_id=kakao_id).first()
    print(user_row)
    if user_row is None:
        print("SDSD")
        return abort(404)

    session["user"] = user_row.as_dict()




    return make_response("", 200)



@user_bp.route('/logout')
def logout():
    if "user" in session:
        del session["user"]
    return redirect(url_for('board.munhak_board_list'))

templates/quiz/layout.html
<!DOCTYPE HTML>
<html lang="kr">
<head>
    <meta name="google-site-verification" content="ZuC80xg3UME3ao9EtYCQJUbccygdekyADXkh4bywMUo"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.js"
            integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.15/lodash.min.js"></script>
    <script src="https://kit.fontawesome.com/43798b0c81.js" crossorigin="anonymous"></script>
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/layout.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/quiz_layout.css') }}">
    <script src="https://kit.fontawesome.com/43798b0c81.js" crossorigin="anonymous"></script>
    {#    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.2/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">#}
    <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@500&display=swap" rel="stylesheet">
    <meta property="og:url" content="https://munhak.herokuapp.com/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="https://munhak.herokuapp.com/images/logo3.png"/>
    <meta property="og:title" content="알아두면 쓸데없는 문학퀴즈"/>
    <meta property="og:description" content="문학 퀴즈를 풀면서 흥취를 즐겨볼까요?"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">

    <title>알아두면 쓸데없는 문학퀴즈 - 문학모아</title>
    {% block style %}{% endblock %}
</head>

<body>
<header>
    {#    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">#}
    {#        <a class="navbar-brand" href="">게시판</a>#}
    {#        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"#}
    {#                aria-controls="navbarCollapse" aria-expanded="true" aria-label="Toggle navigation">#}
    {#            <span class="navbar-toggler-icon"></span>#}
    {#        </button>#}
    {#        <div class="navbar-collapse collapse" id="navbarCollapse" style="">#}
    {#            <ul class="navbar-nav mr-auto">#}
    {#                <li class="nav-item">#}
    {#                    <a class="nav-link" href="">메인</a>#}
    {#                </li>#}
    {##}
    {#            </ul>#}
    {##}
    {#        </div>#}
    {#    </nav>#}
</header>


<main>
    {% block main %}{% endblock %}


</main>
<div id="darkModeIconWrapper" onclick="userTheme(true);">
    <i class="fas fa-sun" id="darkModeIcon"></i>
</div>



{% with messages = get_flashed_messages() %}
    {% if messages %}
        <script>
            var messages = {{ messages | safe }};
            for (var i = 0; i < messages.length; i++) {
                alert(messages[i]);
            }
        </script>
    {% endif %}
{% endwith %}

{% block script %}



{% endblock %}

<script>
      function setCookie(cookie_name, value, days) {
            var exdate = new Date();
            exdate.setDate(exdate.getDate() + days);
            // 설정 일수만큼 현재시간에 만료값으로 지정

            var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
            document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
        }

    function getCookie(cookieName) {
        var cookieValue = null;
        if (document.cookie) {
            var array = document.cookie.split((escape(cookieName) + '='));
            if (array.length >= 2) {
                var arraySub = array[1].split(';');
                cookieValue = unescape(arraySub[0]);
            }
        }
        return cookieValue;
    }


    function userTheme(toggle = false) {


        let userMode = localStorage.userThemeMode || 'auto';
        userNode = getCookie("userTheme") || 'auto';

        const osMode = !!window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? 'dark' : 'light';
        if (toggle) {
            switch (userMode) {
                case 'auto':

                    if (osMode === "dark") {
                        userMode = "light";
                    } else {
                        userMode = "dark";
                    }

                    break;
                case 'dark':
                    userMode = 'light';
                    break;
                default:
                    userMode = 'dark';
                    break;
            }
            localStorage.userThemeMode = userMode;
            setCookie("userTheme", userMode, 1000);
        }
        console.log(`current mode : ${userMode}`);
        window.__THEME_MODE = userMode === 'auto' ? osMode : userMode;
        document.getElementsByTagName('body')[0].classList[window.__THEME_MODE === 'dark' ? 'add' : 'remove']('dark-mode');
        if (window.__THEME_MODE === 'dark') {
            $("#darkModeIcon").addClass("fa-moon");
            $("#darkModeIcon").removeClass("fa-sun");
        } else {
            $("#darkModeIcon").addClass("fa-sun");
            $("#darkModeIcon").removeClass("fa-moon");
        }


    }

    if (!!window.matchMedia) {
        ['light', 'dark'].forEach(mode => {
            window.matchMedia(`(prefers-color-scheme: ${mode})`).addListener(e => {
                if (!!e.matches) {
                    userTheme();
                }
            });
        });
    }
    userTheme();

</script>

</body>
</html>

templates/quiz/render_ranking.html
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/ranking.css') }}">
<div class="rankingText">
    순위표
</div>
<table id="rankingTable">
    <tr>
        <th class="rankingNo">
            #
        </th>
        <th class="rankingNickname">
            별명(닉네임)
        </th>
        <th class="rankingScore">
            최고 점수
        </th>
    </tr>



    {% for record_row in data.record_rows %}
        <tr>
            <td>
                {{ loop.index }}
            </td>
            <td>
                {{ record_row.nickname }}
            </td>
            <td>
                {{ record_row.score }}
            </td>


        </tr>

    {% endfor %}

</table>

<br>

{% if data.my_row != None %}

    <div class="rankingText">
        나의 등수
    </div>

    <table id="rankingMyTable">

        <tr>
            <td class="rankingNo">
                {{ data.my_row.no }}
            </td>
            <td class="rankingNickname">
                {{ data.my_row.nickname }}
            </td>
            <td class="rankingScore">
                {{ data.my_row.score }}
            </td>


        </tr>
    </table>


{% endif %}


{% if "user" not in session %}
    <div class="rankingBottomText">

        로그인하면 순위표에 오를 수 있어요! &nbsp;&nbsp;
        <a class="btn btn-light" id="goLoginButtonRanking">
            로그인 / 회원가입
        </a>
    </div>



{% endif %}


<script>
    function setCookie(cookie_name, value, days) {
        var exdate = new Date();
        exdate.setDate(exdate.getDate() + days);
        // 설정 일수만큼 현재시간에 만료값으로 지정

        var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
        document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
    }

    $("#goLoginButtonRanking").on("click", function () {
        setCookie("after-login-redirect", location.href);
        location.href = "{{ url_for("user.login_form") }}"
    })

</script>

templates/quiz/result.html
{% extends "quiz/layout.html" %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/quiz.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/ranking.css') }}">
    <title>알아두면 쓸데없는 문학퀴즈 - 문학모아</title>
{% endblock %}

{% block main %}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <div id="container">
        <div id="content">
            <hr>
            {% if data.is_success %}
                <div class="message">
                    모든 문제를 맞히셨습니다!
                </div>
            {% else %}
                <div class="message">
                    이런..
                </div>
                <div id="hint">
                    <q>&nbsp;{{ data.current_munhak.hint }}&nbsp;</q>는..
                </div>
                <div class="sourceMessage">
                    < {{ data.current_munhak.source }} >
                </div>
                <a href="{{ url_for('board.munhak_board_detail', munhak_seq=data.current_munhak.munhak_seq) }}">
                    <div id="option{{ data.correct + 1 }}" class="option optionResult"
                         data="{{ data.correct_option.writer }}, 『{{ data.correct_option.title }}』"
                         title="{{ data.correct_option.title }}">
                        {{ data.correct_option.writer }}, 『{{ data.correct_option.title }}』
                    </div>

                </a>

                <div id="message">
                    이었습니다!
                </div>


            {% endif %}
            <div class="message">
                총 {{ data.solved_count }}개를 맞히셨어요!
            </div>

            {% if "user" not in session and data.solved_count >= 1 %}
                <div id="goLoginButton">
                    로그인하고 순위표 등록하기
                </div>
            {% endif %}


            <div id="share">
                공유 : <a id="kakao-link-btn" href="javascript:sendLink()">
                <img
                        src="https://developers.kakao.com/assets/img/about/logos/kakaolink/kakaolink_btn_medium.png"
                />
            </a>
            </div>


            <a id="startButton" class="btn btn-primary" href="{{ url_for("quiz.quiz") }}">다시하기</a>


            <script type="text/javascript">
                Kakao.init("7c6363be08358dc7ce7079459bfe67de");

                function sendLink() {

                    Kakao.Link.sendDefault({
                        objectType: 'feed',
                        content: {
                            title: "알아두면 쓸데없는 문학퀴즈",
                            description: `알쓸문학에서 {{ data.solved_count }}개를 맞혔어요!`,
                            imageUrl:
                                'https://munhak.herokuapp.com/images/logo3.png',
                            link: {
                                mobileWebUrl: 'https://munhak.herokuapp.com/quiz',
                                webUrl: 'https://munhak.herokuapp.com/quiz',
                            },
                        },
                        buttons: [
                            {
                                title: '웹으로 보기',
                                link: {
                                    mobileWebUrl: 'https://munhak.herokuapp.com/quiz',
                                    webUrl: 'https://munhak.herokuapp.com/quiz',
                                },
                            },
                        ],
                    })

                }
            </script>


        </div>
    </div>

    <div class="modal fade" id="rankingModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <div class="modal-body rankingModalBody">

                </div>

            </div>
        </div>
    </div>


    <div id="goPrevPage">
        <div class="btn btn-outline-secondary">
            <i class="fas fa-arrow-left"></i> 이전으로
        </div>


    </div>


    <div id="openRanking">
        <i class="fas fa-trophy"></i>
    </div>

{% endblock %}

{% block script %}
    <script>

        $("#goPrevPage").on("click", function () {
            location.href = "{{ url_for("quiz.index") }}"
        });


        let is_best_record = {{ "true" if data.is_best_record == True else "false" }}



            $(document).ready(function () {
                if (is_best_record == true) {
                    toastr.options = {
                        "closeButton": true,
                        "debug": false,
                        "newestOnTop": true,
                        "progressBar": false,
                        "positionClass": "toast-top-center",
                        "preventDuplicates": true,
                        "onclick": null,
                        "showDuration": "300",
                        "hideDuration": "1000",
                        "timeOut": "2000",
                        "extendedTimeOut": "1000",
                        "showEasing": "swing",
                        "hideEasing": "linear",
                        "showMethod": "fadeIn",
                        "hideMethod": "fadeOut"
                    }
                    toastr["success"]("최고기록 갱신!", "알림")
                }
            })


        function setCookie(cookie_name, value, days) {
            var exdate = new Date();
            exdate.setDate(exdate.getDate() + days);
            // 설정 일수만큼 현재시간에 만료값으로 지정

            var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
            document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
        }

        $("#goLoginButton").on("click", function () {
            setCookie("after-login-redirect", "{{ url_for("quiz.result") }}");
            location.href = "{{ url_for("user.login_form") }}"
        })


        $(".optionResult").hover(function () {
            $(this).html(`『${$(this).attr("title")}』 더 공부하러 가기`);
        }, function () {
            $(this).html($(this).attr("data"));
        })


        $("#openRanking").on("click", function () {
            $("#rankingModal").modal();
            $.ajax({
                type: "GET",
                url: "./render-ranking",
                statusCode: {
                    404: function (data) {
                        location.href = "./result";
                    },
                    200: function (data) {
                        console.log(data);
                        $(".rankingModalBody").html(data);

                    }
                }

            })
        })
        $(document).ready(function () {

        })


    </script>


{% endblock %}