app/board/views.py
from flask import Blueprint, make_response
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file
import socket
import base64
import os
import random
import copy
from sqlalchemy import func, desc
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple, defaultdict
from flask_restful import Api, Resource, reqparse
import re
from app.common.decorator import login_required, return_500_if_errors
from config import credentials, SECRET_KEY, YOUTUBE_KEY
from app.cache import cache
from app.common.function import *
import requests
from app.db import *

from datetime import datetime
from itertools import groupby

board_bp = Blueprint('board', __name__)


@board_bp.route('/test')
def test():
    return render_template("test.html")


@board_bp.route('/board/detail/<int:munhak_seq>/<munhak_title>/')
@board_bp.route('/board/detail/<int:munhak_seq>/', defaults={'munhak_title': None})
def munhak_board_detail(munhak_seq, munhak_title):
    # import time
    # time.sleep(2)

    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows = copy.deepcopy(munhak_rows_data)

    target_munhak_row = None
    for munhak_row in munhak_rows:
        if munhak_row["munhak_seq"] == munhak_seq:
            target_munhak_row = munhak_row

    if target_munhak_row is None:
        return render_template("munhak_board_detail_404.html")

    if munhak_title != format_url_title(target_munhak_row["title"]):
        return redirect(url_for('board.munhak_board_detail', munhak_seq=munhak_seq,
                                munhak_title=format_url_title(target_munhak_row["title"])))

    if "user" in session:
        user_seq = session["user"]["user_seq"]
    else:
        user_seq = -1

    munhak_video_rows = Video.query.filter_by(munhak_seq=target_munhak_row["munhak_seq"]).all()
    exam_video_rows = Video.query.filter_by(munhak_source=target_munhak_row["source"]).all()

    munhak_video_list = [
        dict(video_row.as_dict(), **{"is_mine": "true" if video_row.user_seq == user_seq else "false"}) for video_row
        in munhak_video_rows]
    exam_video_list = [
        dict(video_row.as_dict(), **{"is_mine": "true" if video_row.user_seq == user_seq else "false"}) for video_row
        in exam_video_rows]

    tag_rows = db.session.query(Tag, func.count(Like.like_seq).label("like_count"),
                                func.count(Like.like_seq).filter(Like.user_seq == user_seq).label("liked")

                                ).outerjoin(
        Like,
        Tag.tag_seq == Like.tag_seq).filter(Tag.munhak_seq == munhak_seq).group_by(Tag.tag_seq).order_by(
        desc("like_count")).all()

    tip_rows = db.session.query(Tip, func.count(Like.like_seq).label("like_count"),
                                func.count(Like.like_seq).filter(Like.user_seq == user_seq).label("liked")

                                ).outerjoin(
        Like,
        Tip.tip_seq == Like.tip_seq).filter(Tip.munhak_seq == munhak_seq).group_by(Tip.tip_seq).order_by(
        desc("like_count")).all()

    # return "DD"
    tips = [dict(tip_row.Tip.as_dict(),
                 **{"like_count": tip_row.like_count, "liked": "true" if tip_row.liked == 1 else "false",
                    "is_mine": "true" if tip_row.Tip.user_seq == user_seq else "false",
                    "user_nickname": tip_row.Tip.user.nickname}, ) for
            tip_row in tip_rows]

    tip_mine_exist = False
    for tip in tips:
        tip_mine_exist = tip_mine_exist or (tip["is_mine"] == "true")

    try:
        subject_last_word = target_munhak_row["subject"].split()[-1]
    except:
        subject_last_word = "N"
    print(subject_last_word)
    related_list = [munhak_row for munhak_row in munhak_rows
                    if (
                            munhak_row["title"] in target_munhak_row["title"] or
                            (target_munhak_row["writer"] != "작자 미상" and
                             munhak_row["writer"] == target_munhak_row["writer"]) or
                            target_munhak_row["title"] in munhak_row["title"]
                    ) and (munhak_row["munhak_seq"] != target_munhak_row["munhak_seq"])]

    related_list_subject = [munhak_row for munhak_row in munhak_rows if
                            (subject_last_word in munhak_row["subject"].split(" ")) and (
                                    munhak_row["munhak_seq"] != target_munhak_row[
                                "munhak_seq"]) and munhak_row not in related_list]

    random.shuffle(related_list_subject)
    related_list_subject = related_list_subject[:min(5, len(related_list_subject))]

    # related_list = list(related_list)
    print(related_list)

    data = {
        "munhak_seq": munhak_seq,
        "title": target_munhak_row["title"],
        "writer": target_munhak_row["writer"],
        "source": target_munhak_row["source"],
        "category": target_munhak_row["category"],
        "munhak_video_list": munhak_video_list,
        "exam_video_list": exam_video_list,
        "subject": target_munhak_row["subject"],
        "tags": [dict(tag_row.Tag.as_dict(),
                      **{"like_count": tag_row.like_count, "liked": "true" if tag_row.liked == 1 else "false",
                         "is_mine": "true" if tag_row.Tag.user_seq == user_seq else "false"}) for
                 tag_row in tag_rows],
        "tips": tips,
        "tip_mine_exist": tip_mine_exist,
        "related_list": related_list,
        "related_list_subject": related_list_subject
    }
    print(request.url)
    r = make_response(render_template("munhak_board_detail.html", data=data))
    r.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')

    return r


@board_bp.route('/board/render-card')
def munhak_board_render_card():
    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows = copy.deepcopy(munhak_rows_data)

    args = request.args
    query = args.get("q", "")
    # tags = args.get("tags", None)

    query_list = query.split()
    origin_query_list = copy.deepcopy(query_list)
    try:
        page = int(args.get("page", 1))
    except:
        page = 1
    page_size = 10
    # query_list.remove("#")
    print(query)
    print(query_list)
    query_source_list = [word[1:].replace("-", " ") for word in query_list if word[0] == "@"]
    print("qsl", query_source_list)
    query_category_list = [word[1:] for word in query_list if word[0] == "$"]
    print("qcl", query_category_list)

    query_list = [word for word in query_list if word[0] != "@" and word[0] != "$"]

    if len(query_list) != 0:
        query_munhak_seq_set = set()

        for word in query_list:

            if word[0] != "#":
                for munhak_row in munhak_rows:
                    if word in munhak_row["title"].replace(" ", "") or word == munhak_row["writer"]:
                        query_munhak_seq_set.add(munhak_row["munhak_seq"])

        print(Tag.query.filter(
            Tag.tag_name.in_([word[1:] for word in query_list if word[0] == "#"])).all())

        tag_rows = Tag.query.filter(
            Tag.tag_name.in_([word[1:] for word in query_list if word[0] == "#"])).all()

        for tag_row in tag_rows:
            query_munhak_seq_set.add(tag_row.munhak_seq)
        # query_munhak_seq_set.add()

        print(query_munhak_seq_set)

        query_munhak_rows = [
            [munhak_row for munhak_row in munhak_rows if munhak_seq == munhak_row["munhak_seq"]][0] for munhak_seq in
            query_munhak_seq_set]
        print(query_munhak_rows)

    else:
        query_munhak_rows = munhak_rows

    query_munhak_rows = [
        munhak_row for munhak_row in query_munhak_rows if munhak_row["source"] in query_source_list and munhak_row[
            "category"] in query_category_list]

    query_munhak_rows = sorted(query_munhak_rows, key=lambda x: (x["source"][:5], x["source"]), reverse=True)

    data = {
        "page": page,
        "max_page": (len(query_munhak_rows) - 1) // page_size + 1,
        "query": query,
        "munhak_rows": [
            {
                "munhak_seq": munhak_row["munhak_seq"],
                "title": munhak_row["title"],
                "writer": munhak_row["writer"],
                "source": munhak_row["source"],
                "category": munhak_row["category"],
                "tags": [tag_row.tag_name for tag_row in
                         db.session.query(Tag)
                             .outerjoin(Like, Tag.tag_seq == Like.tag_seq)
                             .filter(Tag.munhak_seq == munhak_row["munhak_seq"])
                             .group_by(Tag.tag_seq)
                             .order_by(desc(func.count(Like.like_seq).label("like_count")))
                             .all()
                         ][:5],

            } for munhak_row in query_munhak_rows[(page - 1) * page_size:  page * page_size]
        ],
        "search_query_tags": [word[1:] for word in query_list if word[0] == "#"],
        "total_rows": len(query_munhak_rows)
    }
    print([word[1:] for word in query_list if word[0] == "#"])
    resp = make_response(render_template("munhak_board_card.html", data=data))

    query_cookie = " ".join(origin_query_list)
    resp.set_cookie('query', base64.b64encode(query_cookie.encode("UTF-8")))
    # print( )

    return resp


@board_bp.route('/board/random-munhak')
def random_munhak():
    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows = copy.deepcopy(munhak_rows_data)

    random_munhak_row = random.choice(munhak_rows)

    return redirect(url_for("board.munhak_board_detail", munhak_seq=random_munhak_row["munhak_seq"]))


@board_bp.route('/board')
def munhak_board_list():
    cookies = request.cookies

app/reading_quiz/views.py
from flask import Blueprint, make_response
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file
import socket
from datetime import datetime
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple
from flask_restful import Api, Resource, reqparse
from sqlalchemy import func, desc, asc

from app.common.decorator import return_500_if_errors, login_required
from app.db import *
from config import credentials, SECRET_KEY
from app.cache import cache
from app.common.function import fetch_spread_sheet, format_url_title, send_discord_alert_log
from config import SECRET_KEY

reading_quiz_bp = Blueprint('reading_quiz', __name__)


@reading_quiz_bp.route('/list')
def reading_quiz_list():
    data = {}

    # munhak_rows = ContentQuizMunhak.query.all()
    #
    # munhak_list = [x.as_dict() for x in munhak_rows]
    munhak_rows = db.session.query(ContentQuizMunhak, func.count(ContentQuiz.quiz_seq).label("quiz_count")).outerjoin(
        ContentQuiz,
        ContentQuiz.munhak_seq == ContentQuizMunhak.munhak_seq).group_by(ContentQuizMunhak.munhak_seq) \
        .order_by(desc(ContentQuizMunhak.add_date), asc(ContentQuizMunhak.munhak_seq)).all()

    print(munhak_rows)

    # # return "DD"
    # tips = [dict(tip_row.Tip.as_dict(),
    #              **{"like_count": tip_row.like_count, "liked": "true" if tip_row.liked == 1 else "false",
    #                 "is_mine": "true" if tip_row.Tip.user_seq == user_seq else "false",
    #                 "user_nickname": tip_row.Tip.user.nickname}, ) for
    #         tip_row in tip_rows]

    data["munhak_list"] = munhak_rows

    print(data)

    resp = make_response(render_template("reading_quiz_list.html", data=data))
    resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return resp


@reading_quiz_bp.route('/detail/<int:munhak_seq>/<munhak_title>/')
@reading_quiz_bp.route('/detail/<int:munhak_seq>/', defaults={'munhak_title': None})
def reading_quiz_detail(munhak_seq, munhak_title):
    if "user" in session:
        user_seq = session["user"]["user_seq"]
    else:
        user_seq = -1

    munhak_rows = ContentQuizMunhak.query.all()

    target_munhak_row = None
    for munhak_row in munhak_rows:
        if munhak_row.munhak_seq == munhak_seq:
            target_munhak_row = munhak_row

    if target_munhak_row is None:
        return render_template("munhak_board_detail_404.html")

    if munhak_title != format_url_title(target_munhak_row.title):
        return redirect(url_for('reading_quiz.reading_quiz_detail', munhak_seq=munhak_seq,
                                munhak_title=format_url_title(target_munhak_row.title)))

    quiz_rows = ContentQuiz.query.filter_by(munhak_seq=munhak_seq).all()

    quiz_list = [dict(quiz_row.as_dict(),
                      **{
                          "is_mine": "true" if quiz_row.user_seq == user_seq else "false",
                          "user_nickname": quiz_row.user.nickname}, ) for
                 quiz_row in quiz_rows]

    print(quiz_list)

    quiz_mine_exist = False
    for quiz in quiz_list:
        quiz_mine_exist = quiz_mine_exist or (quiz["is_mine"] == "true")

    data = {
        "munhak_row": target_munhak_row,
        "quiz_list": quiz_list,
        "quiz_mine_exist": quiz_mine_exist,
    }

    r = make_response(render_template("reading_quiz_detail.html", data=data))
    r.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return r


@reading_quiz_bp.route("/add", methods=["GET", "POST"])
@login_required
def add_reading_quiz():
    args = request.form
    munhak_seq = args.get("munhak_seq", None)
    content = args.get("content", None)
    print(args)
    if munhak_seq is None or not munhak_seq.isdigit() or content is None or type(content) != str:
        return abort(400)
    if not (1 <= len(content) <= 1000):
        return abort(400)
    munhak_seq = int(munhak_seq)

    munhak_row = ContentQuizMunhak.query.filter_by(munhak_seq=munhak_seq).first()
    if munhak_row is None:
        return abort(404)

    user_seq = session["user"]["user_seq"]

    old_quiz_row = ContentQuiz.query.filter_by(user_seq=user_seq, munhak_seq=munhak_seq).first()
    if old_quiz_row is not None:
        return abort(409)

    quiz_row = ContentQuiz(
        quiz_content=content,
        user_seq=user_seq,
        munhak_seq=munhak_seq,
        add_date=datetime.now(),
    )

    db.session.add(quiz_row)
    db.session.commit()

    send_discord_alert_log(f"새로운 퀴즈 추가! {quiz_row.munhak.title}")

    return "", 200


@reading_quiz_bp.route("/edit", methods=["GET", "POST"])
@login_required
def edit_reading_quiz():
    args = request.form
    munhak_seq = args.get("munhak_seq", None)
    content = args.get("content", None)
    print(args)
    if munhak_seq is None or not munhak_seq.isdigit() or content is None or type(content) != str:
        return abort(400)
    if not (1 <= len(content) <= 1000):
        return abort(400)
    munhak_seq = int(munhak_seq)

    munhak_row = ContentQuizMunhak.query.filter_by(munhak_seq=munhak_seq).first()
    if munhak_row is None:
        return abort(404)

    user_seq = session["user"]["user_seq"]

    old_quiz_row = ContentQuiz.query.filter_by(user_seq=user_seq, munhak_seq=munhak_seq).first()
    if old_quiz_row is None:
        return abort(404)

    old_quiz_row.quiz_content = content

    db.session.commit()

    send_discord_alert_log(f"퀴즈 수정! {old_quiz_row.munhak.title}")

    return "", 200


@reading_quiz_bp.route("/delete", methods=["GET", "POST"])
@login_required
def delete_reading_quiz():
    args = request.form
    reading_quiz_seq = args.get("reading_quiz_seq", None)
    print(args)
    if reading_quiz_seq is None or not reading_quiz_seq.isdigit():
        return abort(400)

    reading_quiz_seq = int(reading_quiz_seq)
    user_seq = session["user"]["user_seq"]

    old_quiz_row = ContentQuiz.query.filter_by(user_seq=user_seq, quiz_seq=reading_quiz_seq).first()
    if old_quiz_row is None:
        return abort(404)

    db.session.delete(old_quiz_row)
    db.session.commit()
    return "", 200


@reading_quiz_bp.route("/write/<int:munhak_seq>", methods=["GET", "POST"])
@login_required
def write_reading_quiz_form(munhak_seq):
    munhak_seq = munhak_seq

    munhak_rows_data = cache.get("munhak_rows_data")
    munhak_rows = copy.deepcopy(munhak_rows_data)

    munhak_row = ContentQuizMunhak.query.filter_by(munhak_seq=munhak_seq).first()
    if munhak_row is None:
        return abort(404)

    data = {
        "munhak_row": munhak_row
    }

    user_seq = session["user"]["user_seq"]
    quiz_row = ContentQuiz.query.filter_by(munhak_seq=munhak_seq, user_seq=user_seq).first()

    if quiz_row is not None:
        data["content"] = quiz_row.quiz_content
        print(data["content"])

    return render_template("reading_quiz_form.html", data=data)

templates/index.html
{% extends "layout.html" %}


{% block style %}
    <title>문학모아 : 모두의 문학 나눔터</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">
{% endblock %}

{% block main %}
    <div id="contentContainer">
        <div id="centerContent">

            <h1>
                모두가 함께 모아가는 문학 나눔터,
            </h1>
            <h2>
                문학모아에 오신 것을 환영합니다!
            </h2>

            <div class="btn btn-outline-secondary" id="goRandomMunhak">
                <i class="fas fa-random"></i>&nbsp;아무 문학이나 일단 둘러보기
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>



        $("#goRandomMunhak").on("click", function () {
            {#location.href=`{{ url_for("board.random_munhak") }}`#}

            movePage(`{{ url_for("board.random_munhak") }}`);

        })




    </script>


{% endblock %}

templates/munhak_board_card.html
{% for munhak_row in data.munhak_rows %}
    <a class="munhakCardWrapper"
       munhak_seq="{{ munhak_row.munhak_seq }}" page="{{ data.page }}">
        <div class="munhakCard">

            <div class="upperText">
                {{ munhak_row.writer }}, 『{{ munhak_row.title }}』
            </div>
            <div class="bottomText">
                     <span class="source">
                     {{ munhak_row.source }}
                </span>
                &nbsp;·&nbsp;
                <span class="category">
                    {{ munhak_row.category }}
                </span>
            </div>

            <div class="searchResultTagContainer">
                {% for tag in munhak_row.tags %}

                    <span class="tag searchResultTag {{ "searchQueryTag" if tag in data.search_query_tags else "" }}">
                        #&nbsp;{{ tag }}
                    </span>
                {% endfor %}
            </div>

        </div>
    </a>
{% endfor %}

<div class="hiddenValue" key="maxPage" value="{{ data.max_page }}">
</div>

<div class="hiddenValue" key="totalRows" value="{{ data.total_rows }}">
</div>


<script>

    function setCookie(cookie_name, value, days) {
        var exdate = new Date();
        exdate.setDate(exdate.getDate() + days);
        // 설정 일수만큼 현재시간에 만료값으로 지정

        var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
        document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
    }

    $(".munhakCardWrapper").on("click", function () {

        setCookie("page", $(this).attr("page"), 1)
        {#location.href = `/board/detail/${$(this).attr("munhak_seq")}`#}
        movePage(`/board/detail/${$(this).attr("munhak_seq")}`);
    })


</script>

templates/munhak_board_detail_404.html
{% extends "layout.html" %}


{% block style %}
    <title>404 - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">
{% endblock %}

{% block main %}
    <div id="contentContainer">
       <h1>
           못 찾겠다 꾀꼬리
       </h1>
    </div>

{% endblock %}

{% block script %}
    <script>



    </script>
{% endblock %}

templates/reading_quiz_detail.html
{% extends "layout.html" %}


{% block style %}
    <title>독서퀴즈 : {{ data.munhak_row.title }}({{ data.munhak_row.writer }}) - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/reading_quiz.css') }}">
{% endblock %}

{% block main %}
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/reading_quiz.css') }}">
    <div id="contentContainer">
        <div id="title">
            {{ data.munhak_row.title }}
        </div>

        <div class="d-flex justify-content-between">
            <div id="writer">
                {{ data.munhak_row.writer }}
            </div>

            <div id="category_source">
                <span id="source">
                     {{ data.munhak_row.remark }}
                </span>
            </div>
        </div>
        <div id="bottomContent">
            {% if data.munhak_row.sheet_munhak_seq != None %}
            <div class="pgContainer">

                <div class="pgContent">
                    <div id="relatedContainer">


                        <i class="fas fa-link"></i>


                            <a onClick="movePage(`{{ url_for('board.munhak_board_detail', munhak_seq=data.munhak_row.sheet_munhak_seq) }}`);">
                            <span class="related">
                                {{ data.munhak_row.writer }}, 『{{ data.munhak_row.title }}』
                            </span>

                            </a>


                    </div>

                </div>
            </div>
            {% endif %}

            <div class="pgContainer">
                <div class="pgTitle">
                    독서 퀴즈
                </div>

                <div class="pgContent">
                    <div id="readingQuizContainer" style="display: none">


                        {% for quiz in data.quiz_list %}

                            <div class="readingQuizWrapper" data-toggle="false" reading_quiz_seq="{{ quiz.quiz_seq }}"
                                 is_mine={{ quiz.is_mine }}>
                                <div class="readingQuiz md_post">
                                    {{ quiz.quiz_content | markdown }}

                                    <div class="bottomQuizInfo">
                                        <div>
                                            <span class="readingQuizWriterNickname">
                                                작성자 : {{ quiz.user_nickname }}
                                            </span>
                                            {% if quiz.is_mine == "true" %}
                                                &nbsp; &nbsp;

                                                <span class="btn btn-outline-secondary editReadingQuizButton">
                                                    수정
                                                 </span>

                                                <span class="btn btn-outline-danger deleteReadingQuizButton">
                                                    삭제
                                                </span>
                                            {% endif %}

                                        </div>

                                    </div>


                                </div>


                            </div>



                        {% endfor %}

                        {% if data.quiz_mine_exist == False %}
                            <div id="addReadingQuizWrapper">
                                <div id="addReadingQuiz">
                                    + 추가하기
                                </div>
                            </div>
                        {% endif %}

                    </div>


                </div>
            </div>


        </div>

    </div>



    <script>
        (() => {
            function cho_hangul(str) {
                cho = ["ㄱ", "ㄲ", "ㄴ", "ㄷ", "ㄸ", "ㄹ", "ㅁ", "ㅂ", "ㅃ", "ㅅ", "ㅆ", "ㅇ", "ㅈ", "ㅉ", "ㅊ", "ㅋ", "ㅌ", "ㅍ", "ㅎ"];
                result = "";
                for (i = 0; i < str.length; i++) {

                    code = str.charCodeAt(i) - 44032;
                    if (code > -1 && code < 11172) result += cho[Math.floor(code / 588)];
                    else {
                        if (str.charAt(i) != " ") {

                            result += "_";
                        } else {
                            result += " ";
                        }


                    }
                }
                return result;
            }

            $(document).ready(function () {
                $(".readingQuiz").each(function (index, item) {
                    let html = $(item).html();

                    html = html.replaceAll("[[", `
                        <span class="readingQuizBlank" status="0" answer="
                    `)
                    html = html.replaceAll("]]", `
                    ">  ?  </span>
                    `)


                    html = html.replaceAll("((", `
                        <span class="readingQuizOX" status="0" answer="
                    `)
                    html = html.replaceAll("))", `
                    ">  ?  </span>
                    `)

                    $(item).html(html)

                })

                $("#readingQuizContainer").css("display", "unset");


                $(".readingQuizBlank").on("click", function () {
                    $(this).attr("status", (($(this).attr("status") * 1) + 1) % 3)
                    switch ($(this).attr("status") * 1) {
                        case 0:
                            $(this).text("  ?  ");
                            break;
                        case 1:
                            $(this).text(cho_hangul($(this).attr("answer").trim()));
                            break;
                        case 2:
                            $(this).text($(this).attr("answer").trim())
                            break;
                    }

                })

                $(".readingQuizOX").on("click", function () {
                    $(this).attr("status", (($(this).attr("status") * 1) + 1) % 2)
                    switch ($(this).attr("status") * 1) {
                        case 0:
                            $(this).text("  ?  ");
                            break;
                        case 1:
                            let answer = $(this).attr("answer").trim();
                            if (answer == "O" || answer == "o") {
                                $(this).html(`
                                           <i class="far fa-circle readingQuizAnswerO"></i>
                                 `)
                            } else if (answer == "X" || answer == 'x') {
                                $(this).html(`
                                           <i class="fas fa-times readingQuizAnswerX"></i>
                                 `)
                            } else {
                                $(this).text($(this).attr("answer").trim())
                            }


                            break;
                    }

                })
            });


            let is_logined = {{ "true" if "user" in session else "false"}};

            function warningToast(message) {
                toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "newestOnTop": true,
                    "progressBar": false,
                    "positionClass": "toast-top-right",
                    "preventDuplicates": true,
                    "onclick": null,
                    "showDuration": "300",
                    "hideDuration": "1000",
                    "timeOut": "2000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
                }
                toastr["warning"](message, "오류")
            }

            function not_logined() {
                warningToast("로그인이 필요합니다!");
            }

            $("#addReadingQuiz").on("click", function () {


                if (!is_logined) {
                    not_logined();
                    return;
                }

                location.href = `{{ url_for("reading_quiz.write_reading_quiz_form", munhak_seq = data.munhak_row.munhak_seq) }}`
            })

            $(document).on("click", ".editReadingQuizButton", function () {
                if (!is_logined) {
                    not_logined();
                    return;
                }

                location.href = `{{ url_for("reading_quiz.write_reading_quiz_form", munhak_seq = data.munhak_row.munhak_seq) }}`
            })

            $(document).on("click", ".deleteReadingQuizButton", function (e) {
                if (!is_logined) {
                    not_logined();
                    return;
                }

                Swal.fire({
                    title: '경고',
                    text: "정말로 퀴즈를 삭제하시겠어요?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: 'grey',
                    confirmButtonText: '삭제',
                    cancelButtonText: "취소",
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            type: "POST",
                            url: "{{ url_for("reading_quiz.delete_reading_quiz") }}",
                            data: {
                                "reading_quiz_seq": $(e.target).parents(".readingQuizWrapper").attr("reading_quiz_seq")
                            },
                            dataType: "json",
                            statusCode: {
                                404: function (data) {

                                },
                                200: function (data) {
                                    window.location.reload();
                                }
                            }

                        }).done(function (data) {
                            console.log(data);

                        })
                    }
                })
            })
        })();


    </script>

{% endblock %}

{% block script %}

{% endblock %}