app/user/views.py
from flask import Blueprint
from flask import Flask, render_template, session, request, flash, redirect, url_for, Response, abort, jsonify, \
    send_file, make_response
import socket
import os
import random
import copy
# from app.global_var import munhak_rows_data
from flask_sqlalchemy import SQLAlchemy, Model
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json
import base64
from collections import namedtuple
from flask_restful import Api, Resource, reqparse

from app.common.decorator import return_500_if_errors, login_required
from config import credentials, SECRET_KEY, YOUTUBE_KEY
from app.cache import cache
from app.common.function import *
import requests
from app.db import *
import datetime
from datetime import datetime

user_bp = Blueprint('user', __name__)



@user_bp.route("/user/change-nickname", methods=["GET", "POST"])
@login_required
def change_nickname():
    args = request.form
    nickname = args.get("nickname", None)
    if nickname is None or (not (1 <= len(nickname.encode("cp949")) <= 16)):
        return abort(400)
    user_seq = session["user"]["user_seq"]
    user_row = User.query.filter_by(user_seq=user_seq).first()
    if user_row is None:
        return abort(401)

    user_row.nickname = nickname

    db.session.commit()

    session["user"] = user_row.as_dict()
    print(session)
    return jsonify({
        "message" : "정상적으로 처리되었습니다."
    }), 200



@user_bp.route('/my')
@login_required
def my_page():
    print(session["user"]["nickname"])
    resp = make_response(render_template("user/my_page.html"))
    resp.set_cookie('PJAX-URL', base64.b64encode(request.url.encode("UTF-8")), max_age=None, expires=None, path='/')
    return resp





@user_bp.route('/login')
def login_form():
    return render_template('user/login_form.html')



@user_bp.route('/register')
def register_form():
    return render_template('user/register_form.html')



@user_bp.route('/register-query', methods=["GET", "POST"])
def register_query():
    args = request.form
    nickname = args.get("nickname", None)
    if nickname is None or (not (1 <= len(nickname.encode("cp949")) <= 16)):
        return abort(400)
    cookies = request.cookies
    if "kakao-access-token" not in cookies:
        return abort(403)
    access_token = cookies["kakao-access-token"]
    if access_token is None or type(access_token) != str:
        return abort(400)

    res = requests.get("https://kapi.kakao.com/v1/user/access_token_info", headers={
        "Authorization": "Bearer " + access_token
    })

    kakao_id = str(json.loads(res.text)["id"])

    old_user_row = User.query.filter((User.nickname == nickname) | (User.social_id == kakao_id)).first()
    if old_user_row is not None:
        return abort(409)

    user_row = User(
        nickname=nickname,
        social_type="kakao",
        social_id=kakao_id,
        add_date=datetime.now()
    )
    db.session.add(user_row)
    db.session.commit()
    session["user"] = user_row.as_dict()

    send_discord_alert_log(f"새로운 회원! {nickname}")

    return make_response("", 200)



@user_bp.route('/login-query-kakao', methods=["GET", "POST"])
def login_query_kakao():


    args = request.form
    access_token = args.get("access_token", None)
    print(access_token)
    if access_token is None or type(access_token) != str:
        return abort(400)

    res = requests.get("https://kapi.kakao.com/v1/user/access_token_info", headers={
        "Authorization": "Bearer " + access_token
    })

    kakao_id = str(json.loads(res.text)["id"])

    user_row = User.query.filter_by(social_type="kakao", social_id=kakao_id).first()
    print(user_row)
    if user_row is None:
        print("SDSD")
        return abort(404)

    session["user"] = user_row.as_dict()




    return make_response("", 200)



@user_bp.route('/logout')
def logout():
    if "user" in session:
        del session["user"]
    return redirect(url_for('board.munhak_board_list'))

templates/user/login_form.html
{% extends "quiz/layout.html" %}

{% block style %}
    <title>로그인 - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/login_form.css') }}">
    <link rel='stylesheet' href='https://unpkg.com/nprogress@0.2.0/nprogress.css'/>
    <script src='https://unpkg.com/nprogress@0.2.0/nprogress.js'></script>
{% endblock %}

{% block main %}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <div id="container">
        <div id="content">
            <div id="title">
                소셜 계정으로 로그인 / 회원가입
            </div>

            <div id="kakaoLoginButton">

            </div>
        </div>
    </div>



    <script type="text/javascript">
        function setCookie(cookie_name, value, days) {
            var exdate = new Date();
            exdate.setDate(exdate.getDate() + days);
            // 설정 일수만큼 현재시간에 만료값으로 지정

            var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
            document.cookie = cookie_name + '=' + cookie_value;
        }

        function getCookie(cookieName) {
            var cookieValue = null;
            if (document.cookie) {
                var array = document.cookie.split((escape(cookieName) + '='));
                if (array.length >= 2) {
                    var arraySub = array[1].split(';');
                    cookieValue = unescape(arraySub[0]);
                }
            }
            return cookieValue;
        }

        Kakao.init("7c6363be08358dc7ce7079459bfe67de");

        Kakao.Auth.createLoginButton({
            container: '#kakaoLoginButton',
            success: function (response) {
                NProgress.start();
                $.ajax({
                    type: "POST",
                    url: "./login-query-kakao",
                    data: {"access_token": response.access_token},
                    dataType: "json",
                    statusCode: {
                        404: function (data) {

                            setCookie("kakao-access-token", response.access_token, 1);
                            location.href = "{{ url_for("user.register_form") }}";
                        },
                        200: function (data) {

                            if (getCookie("after-login-redirect") != undefined && getCookie("after-login-redirect") != "") {
                                let t = getCookie("after-login-redirect");
                          
                                setCookie('after-login-redirect', '', '-1');
                                NProgress.done();
                       
                                location.href = t;
                            } else {
                                NProgress.done();
                                location.href = "{{ url_for("board.munhak_board_list") }}";
                            }

                        }
                    }
                }).done(function (data) {
                    console.log(data);

                })
            },
            fail: function (error) {
                console.log(error);
            },
        });
    </script>


{% endblock %}



{% block script %}
    <script>

    </script>
{% endblock %}

templates/user/my_page.html
{% extends "layout.html" %}

{% block style %}
    <title>문학모아 : 모두의 문학 나눔터</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/nav.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/munhak_board.css') }}">


{% endblock %}

{% block main %}
    <link rel='stylesheet' href='https://unpkg.com/nprogress@0.2.0/nprogress.css'/>
    <script src='https://unpkg.com/nprogress@0.2.0/nprogress.js'></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/my_page.css') }}">
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">

    <div id="contentContainer">

        <div id="myPageTitle">
            회원 정보
        </div>
        <br>
        <div class="form-group">
            <label for="myPageNicknameInput" id="myPageNicknameLabel">별명(닉네임) : </label>
            {#                <br>#}
            <input type="text" id="myPageNicknameInput">
            <small id="myPageNicknameHelp" class="form-text text-muted">16바이트까지 가능(영문 - 1, 한글 - 2)
                <span id="myPageNicknameLength"></span>
            </small>
        </div>


        <div class="btn btn-secondary" id="changeNicknameButton">
            변경
        </div>
    </div>




    <script type="text/javascript">

        function getCookie(cookieName) {
            var cookieValue = null;
            if (document.cookie) {
                var array = document.cookie.split((escape(cookieName) + '='));
                if (array.length >= 2) {
                    var arraySub = array[1].split(';');
                    cookieValue = unescape(arraySub[0]);
                }
            }
            return cookieValue;
        }

        function getStringLength(str) {
            var retCode = 0;
            var strLength = 0;

            for (i = 0; i < str.length; i++) {
                var code = str.charCodeAt(i)
                var ch = str.substr(i, 1).toUpperCase()

                code = parseInt(code)

                if ((ch < "0" || ch > "9") && (ch < "A" || ch > "Z") && ((code > 255) || (code < 0)))
                    strLength = strLength + 2;
                else
                    strLength = strLength + 1;
            }
            return strLength;
        }

        $("#changeNicknameButton").on("click", function () {
            let nicknameLength = getStringLength($("#myPageNicknameInput").val());
            if (nicknameLength > 16 || nicknameLength < 1) {
                return;
            }
            NProgress.start();
            $.ajax({
                type: "POST",
                url: "/user/change-nickname",
                data: {"nickname": $("#myPageNicknameInput").val()},
                dataType: "json",
                statusCode: {
                    400: function (data) {
                        toastr.options = {
                            "closeButton": true,
                            "debug": false,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "300",
                            "hideDuration": "1000",
                            "timeOut": "2000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr["warning"]("별명(닉네임)은 1~16바이트여야 합니다.", "오류")
                    },
                    409: function (data) {


                        toastr.options = {
                            "closeButton": true,
                            "debug": false,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "300",
                            "hideDuration": "1000",
                            "timeOut": "2000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr["warning"]("별명(닉네임)이 중복되었거나 이미 가입된 계정입니다.", "오류")
                    },
                    403: function (data) {
                        location.href = "{{ url_for("user.login_form") }}"
                    },
                    200: function (data) {
                        location.href = location.href;
                    }
                }
            })
        })


        $("#myPageNicknameInput").on("input", function () {

            let stringByteLength = getStringLength($(this).val());

            $("#myPageNicknameLength").html(
                `(${stringByteLength}/16)`
            )
        })


          function setCookie(cookie_name, value, days) {
            var exdate = new Date();
            exdate.setDate(exdate.getDate() + days);
            // 설정 일수만큼 현재시간에 만료값으로 지정

            var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
            document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
        }


    </script>


{% endblock %}



{% block script %}
    <script>

    </script>
{% endblock %}

templates/user/register_form.html
{% extends "quiz/layout.html" %}

{% block style %}
    <title>회원가입 - 문학모아</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/index.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/login_form.css') }}">
    <link rel='stylesheet' href='https://unpkg.com/nprogress@0.2.0/nprogress.css'/>
    <script src='https://unpkg.com/nprogress@0.2.0/nprogress.js'></script>
{% endblock %}

{% block main %}
    <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
    <div id="container">
        <div id="content">
            <div id="title">
                회원 정보 입력
            </div>

            <div class="form-group">
                <label for="nicknameInput" id="nicknameLabel">별명(닉네임) : </label>
                {#                <br>#}
                <input type="text" id="nicknameInput">
                <small id="nicknameHelp" class="form-text text-muted">16바이트까지 가능(영문 - 1, 한글 - 2)
                    <span id="nicknameLength"></span>
                </small>
            </div>


            <div class="btn btn-secondary" id="registerButton">
                회원가입
            </div>
        </div>
    </div>



    <script type="text/javascript">

        function getCookie(cookieName) {
            var cookieValue = null;
            if (document.cookie) {
                var array = document.cookie.split((escape(cookieName) + '='));
                if (array.length >= 2) {
                    var arraySub = array[1].split(';');
                    cookieValue = unescape(arraySub[0]);
                }
            }
            return cookieValue;
        }

        function getStringLength(str) {
            var retCode = 0;
            var strLength = 0;

            for (i = 0; i < str.length; i++) {
                var code = str.charCodeAt(i)
                var ch = str.substr(i, 1).toUpperCase()

                code = parseInt(code)

                if ((ch < "0" || ch > "9") && (ch < "A" || ch > "Z") && ((code > 255) || (code < 0)))
                    strLength = strLength + 2;
                else
                    strLength = strLength + 1;
            }
            return strLength;
        }

        $("#registerButton").on("click", function () {
            let nicknameLength = getStringLength($("#nicknameInput").val());
            if (nicknameLength > 16 || nicknameLength < 1) {
                return;
            }
            NProgress.start();
            $.ajax({
                type: "POST",
                url: "./register-query",
                data: {"nickname": $("#nicknameInput").val()},
                dataType: "json",
                statusCode: {
                    400: function (data) {
                        toastr.options = {
                            "closeButton": true,
                            "debug": false,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "300",
                            "hideDuration": "1000",
                            "timeOut": "2000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr["warning"]("별명(닉네임)은 1~16바이트여야 합니다.", "오류")
                    },
                    409: function (data) {


                        toastr.options = {
                            "closeButton": true,
                            "debug": false,
                            "newestOnTop": true,
                            "progressBar": false,
                            "positionClass": "toast-top-right",
                            "preventDuplicates": true,
                            "onclick": null,
                            "showDuration": "300",
                            "hideDuration": "1000",
                            "timeOut": "2000",
                            "extendedTimeOut": "1000",
                            "showEasing": "swing",
                            "hideEasing": "linear",
                            "showMethod": "fadeIn",
                            "hideMethod": "fadeOut"
                        }
                        toastr["warning"]("별명(닉네임)이 중복되었거나 이미 가입된 계정입니다.", "오류")
                    },
                    403: function (data) {
                        location.href = "{{ url_for("user.login_form") }}"
                    },
                    200: function (data) {
                        if (getCookie("after-login-redirect") != undefined && getCookie("after-login-redirect") != "") {
                            let t = getCookie("after-login-redirect");
                            setCookie('after-login-redirect', '', '-1');
                            NProgress.done();

                            location.href = t;
                        } else {
                            NProgress.done();
                            location.href = "{{ url_for("board.munhak_board_list") }}";
                        }
                    }
                }
            })
        })


        $("#nicknameInput").on("input", function () {

            let stringByteLength = getStringLength($(this).val());

            $("#nicknameLength").html(
                `(${stringByteLength}/16)`
            )
        })


         function setCookie(cookie_name, value, days) {
            var exdate = new Date();
            exdate.setDate(exdate.getDate() + days);
            // 설정 일수만큼 현재시간에 만료값으로 지정

            var cookie_value = escape(value) + ((days == null) ? '' : ';    expires=' + exdate.toUTCString());
            document.cookie = cookie_name + '=' + cookie_value + ";PATH=/";
        }

        Kakao.init("7c6363be08358dc7ce7079459bfe67de");


    </script>


{% endblock %}



{% block script %}
    <script>

    </script>
{% endblock %}